-- TODO insert SQL statements to create the initial schema
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1000000;

CREATE TABLE PUBLIC.BINARYOBJECT (
  ID BIGINT NOT NULL,
  MODIFICATIONCOUNTER INTEGER NOT NULL,
  DATA BLOB(2147483647),
  SIZE BIGINT NOT NULL,
  MIMETYPE VARCHAR(255),
  PRIMARY KEY (ID)
);